source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'mongoid', '~> 3.1.4'
gem 'simple_form'

#rails generate bootstrap:install less
gem 'less-rails'
gem 'twitter-bootstrap-rails'

#For the cloud map
gem "jqcloud-rails"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'

#For debugging
gem 'awesome_print'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end
